version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=dev-secret-key
      - JWT_SECRET_KEY=jwt-secret-string
      - OPA_URL=http://opa:8181
    depends_on:
      - opa
    volumes:
      - ./src:/app/src
      
  opa:
    image: openpolicyagent/opa:0.57.0-rootless
    platform: linux/arm64
    ports:
      - "8181:8181"
    volumes:
      - ./policies:/policies
    command: 
      - "run"
      - "--server"
      - "--log-format=json"
      - "--log-level=info"
      - "/policies"
      
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - SERVER_URL=http://mcp-server:5000
    depends_on:
      - mcp-server
    volumes:
      - ./src/web:/app/src/web