version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OPA_URL=http://opa:8181
    depends_on:
      - opa
      
  opa:
    image: openpolicyagent/opa:0.57.0-rootless
    platform: linux/arm64
    ports:
      - "8181:8181"
    volumes:
      - ./policies:/policies
    command: 
      - "run"
      - "--server"
      - "--log-format=json"
      - "--log-level=info"
      - "/policies"